<script type="text/javascript">
    $(function(){
        $('#fCadastro').populate(<?php echo $view_json_objeto; ?>);
    });      
</script>
<div class="page" style="padding: 10px;">
    <div class="page-region">
        <div class="page-region-content">
            <h1>Técnicos / Pipeiros</h1>
            <form name="fCadastro" id="fCadastro" action="index.php?Colaborador/atualizar" method="post">
                <input type="hidden" name="ide_colaborador" id="ide_colaborador" />
                <input type="hidden" id="ide_controle" name="ide_controle" value="<?php echo $view_objControle->getId(); ?>"/>
                <h2>Nome</h2>
                <div class="input-control text">
                    <input type="text" name="nom_colaborador" id="nom_colaborador" maxlength="115" required=""/>
                </div>
                <h2>Número CPF</h2>
                <div class="input-control text">
                    <input type="text" name="num_cpf" id="num_cpf" maxlength="14" style="width: 200px;" required=""/>
                </div>
                <h2>Data de Nascimento</h2>
                <div class="input-control text">
                    <input type="text" name="dat_nascimento" id="dat_nascimento" maxlength="10" style="width: 200px;" required=""/>
                </div>
                <h2>Nome da Mãe</h2>
                <div class="input-control text">
                    <input type="text" name="nom_mae" id="nom_mae" maxlength="115" required=""/>
                </div>
                <h2>Email</h2>
                <div class="input-control text">
                    <input type="email" name="des_email" id="des_email" maxlength="115" required=""/>
                </div>
                <h2>Número Telefone 1</h2>
                    <div class="input-control text">
                        <input type="text" name="num_telefone1" id="num_telefone1" maxlength="14" style="width: 200px;" required=""/>
                    </div>
                <h2>Número Telefone 2</h2>
                    <div class="input-control text">
                        <input type="text" name="num_telefone2" id="num_telefone2" maxlength="14" style="width: 200px;"/>
                    </div>
                <h2>Tipo do Técnico</h2>
                <div class="input-control select">
                    <select name="ide_tipo_colaborador" id="ide_tipo_colaborador" required="">
                        <option value="" selected="selected">Selecione</option>
                        <?php echo $view_listTipoColaborador; ?>
                    </select>
                </div>
                <h2>Tipo do Logradouro</h2>
                <div class="input-control select">
                    <select name="ide_tipo_logradouro" id="ide_tipo_logradouro" required="">
                        <option value="" selected="selected">Selecione</option>
                        <?php echo $view_listTipoLogradouro; ?>
                    </select>
                </div>
                <h2><abbr title="Endereço de Domicilio do Técnico">Logradouro</abbr></h2>
                <div class="input-control text">
                    <input type="text" name="nom_logradouro" id="nom_logradouro" maxlength="115" required=""/>
                </div>
                <h2>Número</h2>
                <div class="input-control text">
                    <input type="text" name="num_logradouro" id="num_logradouro" maxlength="10" required="" style="width: 200px;"/>
                </div>
                <h2><abbr title="Ponto de Referência da Localização do Domicílio">Referência</abbr></h2>
                <div class="input-control text">
                    <input type="text" name="des_endereco_referencia" id="des_endereco_referencia" maxlength="115"/>
                </div>
                <h2>Número <abbr title="Código de Endereçamento Postal">CEP</abbr></h2>
                <div class="input-control text">
                    <input type="text" name="num_cep" id="num_cep" maxlength="10" required="" style="width: 200px;"/>
                </div>
                <h2>Município Domicílio</h2>
                <div class="alert-notice"></div>
                <div class="input-control select">
                    <select name="ide_municipio" id="ide_municipio" required="">
                        <option value="" selected="selected">Selecione</option>
                        <?php echo $view_listMunicipio; ?>
                    </select>
                </div>
                <h2>Bairro</h2>
                <div class="input-control select">
                    <select name="ide_bairro" id="ide_bairro" required="" >
                        <option value="" selected="selected">Selecione</option>
                       <?php echo $view_listBairro; ?> 
                    </select>
                </div>
                <label class="checkbox as-block">
                    <input type="checkbox" name="des_status" checked="" value="A"/>
                    <span>Ativar Técnico</span>
                </label>    
                <br/>
                <input type="submit" value="Salvar">
            </form>
        </div>
    </div>
</div>