<div class="page" style="padding: 10px;">
    <h2>Informações do Técnico</h2>
    <div class="page-region">
        <div class="page-region-content">
            
           
            <form name="fCadastro" id="fCadastro" action="index.php?Colaborador/recuperar" method="post">
                <h2>Número CPF</h2>
                <div class="input-control text">
                    <input type="text" name="num_cpf" id="num_cpf" maxlength="14" style="width: 200px;" required=""/>
                </div>
                <div class="input-control text">
                    <input type="submit" value="Recuperar" id="salvar">
                </div>
            </form>    
        </div>
    </div>
</div>
