<div class="page" style="padding: 10px;">
    <div class="page-region">
        <div class="page-region-content">
            <h1>Usuários</h1>
            <div id="notice"></div>
             <?php if($view_listPerfil != null){ ?>
             <form name="fCadastro" id="fCadastro" action="index.php?Usuario/inserir" method="post">
                
                <h2>Colaborador</h2>
                <div class="input-control select">
                    <select name="ide_colaborador" id="ide_colaborador" required="">
                        <option value="" selected="selected">Selecione</option>
                        <?php echo $view_listColaborador; ?>
                    </select>
                </div>
                <h2>Perfil</h2>
                <div class="input-control select">
                    <select id="ide_perfil" name="ide_perfil" required="">
                        <option value="" selected="selected">Selecione</option>
                        <?php  
                            foreach ($view_listPerfil as $objPerfil) {
                                echo "<option value='{$objPerfil->getId()}'>{$objPerfil->getNome()}</option>";
                            }
                        ?>
                    </select>
                </div>
                <h2>Senha Inicial</h2>
                <div class="input-control text">
                    <input type="password" id="des_senha" name="des_senha" maxlength="25" required=""/>
                </div>
                <br/>
                <label class="input-control checkbox">
                    <input type="checkbox" value="A" checked="" id="des_status" name="des_status">
                    <span class="helper">Ativar Usuário</span>
                </label>
                <br/><br/>
                <input type="submit" value="Salvar">
            </form>
            <?php }else{?>
            <h3>Você não tem perfil para cadastrar usuário.</h3>
            <?php } ?>
        </div>
    </div>
</div>