<div class="page" style="padding: 10px;">
    <div class="page-region">
        <div class="page-region-content">
            <h1>Alterar Senha</h1>
            <div id="notice"></div>
          <form name="fCadastro" id="fCadastro" action="index.php?Usuario/alterarSenha" method="post">
                    <h2>Senha Atual</h2>
                    <div class="input-control text">
                        <input type="password" name="des_senha" id="des_senha" maxlength="114" required=""/>
                    </div>
                    <h2>Nova Senha</h2>
                    <div class="input-control text">
                        <input type="password" name="des_senha_new" id="des_senha_new" maxlength="114" required=""/>
                    </div>
                    <h2>Confirme Nova Senha</h2>
                    <div class="input-control text">
                        <input type="password" name="des_senha_conf" id="des_senha_conf" maxlength="114" required=""/>
                    </div>
                    <input type="submit" value="Salvar" >
                </form>
        </div>
    </div>
</div>
