<div class="page secondary">
    <div class="page-header">
        <div class="page-header-content">
            <h1>Oops!<small>Error 404</small></h1>
        </div>
    </div>

    <div class="page-region">
        <div class="page-region-content">
            <p>Ocorreu um problema em sua solicitação. Essa URL não existe em nosso servidor.</p>
            <br/>
            <div style="text-align: center;">
                <img src="<?php echo PATH_IMAGE; ?>404.png" alt="">
            </div>
            
        </div>
    </div>
</div>