<div class="page" style="padding: 10px;">
    <div class="page-region">
        <div class="page-region-content">
            <div style="float: right;"><?php echo $view_objColaborador->getNome(); ?></div> 
            <?php if ($view_listMunicipios != null) { ?>
            <form name="fCadastro" id="fCadastro" action="index.php?Colaborador/listaPorMunicipio" method="post">
                <h1>Lista de Pipeiros</h1>
                <h2>Município</h2>
                <div class="input-control select">
                    <select name="ide_municipio" id="ide_municipio" required="">
                        <option value="" selected="selected">Selecione</option>
                        <?php echo $view_listMunicipios; ?>
                    </select>
                    
                </div>
                 <br/>
                <input type="submit" value="Listar">
                </form>
            <?php }else{?>
            <h2><?php echo $view_nameH2; ?></h2>
            <?php if($view_listPipeiros_top != null): ?>
            <table class="bordered">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Numero CPF</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($view_listPipeiros_top as $objColaborador): ?>
                    <tr>
                        <td><a href="index.php?Colaborador/informar/id/<?php echo $objColaborador->getId(); ?>"><?php echo $objColaborador->getNome(); ?></a></td>
                        <td><?php echo $objColaborador->getNumeroCPF(); ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot></tfoot>
            </table>
            <?php else: ?>
            <h3>Nenhum pipeiro cadastrado</h3>
            <?php endif; ?>
             <?php }?>
        </div>
    </div>
</div>