<div class="page" style="padding: 10px;">
    <div class="page-header ">
        <div class="page-header-content">
            <h1>Entrega<small>Deletar</small></h1>
        </div>
    </div>
    <div class="page-region">
        <div class="page-region-content">
              <form name="fCadastro" id="fCadastro" action="index.php?Entrega/excluir" method="post">
                <h2>Entregas</h2>
                
                <div class="input-control select">
                    <select name="ide_colaborador" id="ide_colaborador" required="">
                        <option value="" selected="selected">Selecione</option>
                        <?php foreach ($view_objColaborador as $objColaborador) {?>
                             <option value="<?php echo $objColaborador->getId();  ?>" ><?php echo $objColaborador->getNome();  ?></option>
                       <?php } ?>
                    </select>
                    
                </div>
                 <br/>
                <input type="submit" value="Excluir">
                </form>
        </div>
    </div>
</div>